Return all gdb output
anfedotoff/gdb-command pull request #27
Opened 2022-11-30 14:27 UTC by Avgor46

2022-12-05 12:09 UTC, SweetVishnya requested changes

2022-12-05 12:14 UTC, anfedotoff requested changes

2022-12-05 12:14 UTC, anfedotoff commented on src/lib.rs
> +    /// Execute gdb and get result without raw stderr
from raw stdout

2022-12-05 12:14 UTC, anfedotoff commented on src/lib.rs
> +    /// Get result for each command.
Result for each executed gdb command from raw gdb output

2022-12-05 12:17 UTC, anfedotoff commented on src/lib.rs
> +    pub fn launch_with_stderr(&self) -> error::Result<Vec<String>> {
This function is not  needed. We could use  `launch` or raw+gdb_result(parse) if we need raw stdout.

2022-12-07 11:58 UTC, anfedotoff approved these changes

2022-12-07 12:18 UTC, SweetVishnya commented on src/lib.rs
> +    /// Result for each executed gdb command from raw gdb output.
Parse result

2022-12-07 13:55 UTC, Avgor46 commented on src/lib.rs
> +    /// Execute gdb and get result from raw stdout
done

2022-12-07 13:56 UTC, anfedotoff approved these changes

2022-12-07 14:03 UTC, SweetVishnya approved these changes

2022-12-07 14:03 UTC, merged